import asyncio

from slack_bolt import App

from ai_agents.design_agent.design_agent import generate_design
from ai_agents.design_agent.figma_generator import generate_figma_design
from ai_agents.jira.comments import add_jira_comment
from ai_agents.jira.mapper import prd_description_text
from ai_agents.state import clear_pending_approval, get_pending_approval


async def _run_design_generation(parent_key: str) -> str:
    pending = get_pending_approval(parent_key)

    if pending is None:
        return f"No pending design request found for `{parent_key}`. It may have already been processed."

    prd_text = f"{pending.prd.title}\n\n{prd_description_text(pending.prd)}"

    design = await generate_design(prd_text)
    figma_result = await generate_figma_design(design)

    await add_jira_comment(
        parent_key,
        f"Figma design generated by the agent: {figma_result.file_url}",
    )

    clear_pending_approval(parent_key)

    return (
        f"Design generated for `{parent_key}`: {figma_result.file_url}\n"
        f"Also added as a comment on the Jira epic."
    )


def register_actions(slack_app: App) -> None:

    @slack_app.action("approve_design_generation")
    def handle_approve_design(ack, body, say, logger):
        ack()

        parent_key = body["actions"][0]["value"]

        try:
            result_text = asyncio.run(_run_design_generation(parent_key))
            say(text=result_text)
        except Exception as error:
            logger.exception(f"Design generation failed for {parent_key}: {error}")
            say(
                text=(
                    f"Design generation failed for `{parent_key}`. "
                    f"If this is a Figma authentication issue, run "
                    f"`scripts/figma_mcp_login.py` to (re)authenticate."
                )
            )

    @slack_app.action("reject_design_generation")
    def handle_reject_design(ack, body, say):
        ack()

        parent_key = body["actions"][0]["value"]
        clear_pending_approval(parent_key)

        say(text=f"Design generation for `{parent_key}` was rejected.")
